
import Head from 'next/head'
import Link from "next/link";
import Footer from './footer'
export default function PageLayout({children, title = "NewsAPP"}) {
    return (
        <>
        <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <header>
    <div> <Link href="/">NewsApi</Link></div>
    <div>
        <Link href="/about">About</Link>
    </div>
    </header>
  <main>{children} </main>
  <style jsx>{`
   header {
    padding: 20px;
    justify-content: space-between;
    display: flex;
   }
   `}</style>
     <Footer/> 
   </>
    )

}