import Head from 'next/head';
import Navigation from './navigations';
export default function PageLayout({ children, title = "NewsAPP" }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset='utf-8' />
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/journal/bootstrap.min.css' />
        <link rel="icon" href="/favicon.ico" />
        <script href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/journal/bootstrap.min.js"></script>
      </Head>
      <Navigation></Navigation>
      <main>{children} </main>
      <style jsx>{`
        header {
        padding: 20px;
        justify-content: space-between;
        display: flex;
      }
      `}</style>

      
    </>
  )

}